version: "3.8"

services:
    web:
        image: ghcr.io/anddddrew/web:latest
        container_name: web
        volumes:
            - .:/usr/src/web
            - /usr/src/web/node_modules
            - /usr/src/web/.next
        restart: always
        ports:
            - "3000:3000"
        links:
            - server

    server:
        image: ghcr.io/anddddrew/server:0.0.2
        container_name: server
        volumes:
            - .:/usr/src/server
        restart: always
        ports:
            - "8000:8000"
        links:
            - redis

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - '6379:6379'