# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["Andrew Nijmeh"]
description = " to api for nijmeh.cloud"
language = "rust"
manifest_version = 2
name = "server"
service_id = ""
