name: build

on:
  - push
  - pull_request

jobs:
  web:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2

      - name: Install deps
        run: pnpm install
      
      - name: Build 
        run: pnpm build

  server:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Cache .cargo/bin
        uses: actions/cache@v3

        env:
          cache-name: cache-cargo
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install sccache
        run: if [ -e ~/.cargo/bin/sccache ] ; then echo "Sccache is already installed"; else cargo install sccache; fi

      - name: Install fleet
        run: if [ -e ~/.cargo/bin/fleet ] ; then echo "Fleet is already installed"; else cargo install fleet-rs; fi

      - name: Run app using fleet
        run: fleet run