[package]
name = "stats"
version = "0.1.0"
description = "API to pull personal stats"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
redis = { version = "0.22.1", features = ["all"] }